// <auto-generated />
namespace Animals_project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Animalss : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Animalss));
        
        string IMigrationMetadata.Id
        {
            get { return "202506021023109_Animalss"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
